stages:
  prepare_annotations:
    cmd: pipenv run python ./src/ner/convert_bliou_to_bio.py ./data/annotation/annotation-result-orig.txt
      ./data/annotation/annotation-result.txt --out data/annotation/annotation-result-BIO.txt
    deps:
      - ./src/ner/convert_bliou_to_bio.py
      - data/annotation/annotation-result-orig.txt
      - data/annotation/annotation-result.txt
    outs:
      - data/annotation/annotation-result-BIO.txt
  prepare_annotations_val:
    cmd: pipenv run python ./src/ner/convert_bliou_to_bio.py ./data/annotation/annotation-result-val.txt
       --out data/annotation/annotation-result-BIO-val.txt
    deps:
      - ./src/ner/convert_bliou_to_bio.py
      - data/annotation/annotation-result-val.txt
    outs:
      - data/annotation/annotation-result-BIO-val.txt    
  prepare_language_model_train_set:
    cmd: pipenv run python ./src/ner/flair/prepare_lm_train_files.py ./data/jobs/seek_vacancies.db
    deps:
      - ./src/ner/flair/prepare_lm_train_files.py
      - data/jobs/seek_vacancies.db
    params:
      - flair.language_model_train.corpus_dir
    outs:
      - data/corpus/jobs/train
  flair_train_ner:
    cmd: pipenv run python ./src/ner/flair/train_ner.py
    deps:
      - src/ner/flair/train_ner.py
      - data/annotation/annotation-result-BIO.txt
      - data/annotation/annotation-result-BIO-val.txt
      - models/jobs_lm_backward
      - models/jobs_lm_forward
    params:
      - flair.ner_train.num_epochs
      - flair.ner_train.crf
      - flair.ner_train.rnn
    outs:
      - models/flair-ner-bert
  prepare_train_ner_dataset_spacy:
    cmd: pipenv run python src/ner/spacy/prepare_traning_data.py data/annotation/annotation-result-orig.json data/annotation/annotation-result.json --out data/annotation/train.spacy
    deps:
      - src/ner/spacy/prepare_traning_data.py
      - data/annotation/annotation-result-orig.json
      - data/annotation/annotation-result.json
    outs:
      - data/annotation/train.spacy
  
  prepare_validation_ner_dataset_spacy:
    cmd: pipenv run python src/ner/spacy/prepare_traning_data.py data/annotation/annotation-result-val.json --out data/annotation/validation.spacy
    deps:
      - src/ner/spacy/prepare_traning_data.py
      - data/annotation/annotation-result-val.json
    outs:
      - data/annotation/validation.spacy

  # spacy_install_eng_model:
  #   cmd: pipenv run python -m spacy download en_core_web_trf

  # spacy_train_ner:
  #   cmd: pipenv run python -m spacy train config/config_gpu.cfg --output ./models/spacy-ner --paths.train ./data/annotation/train.spacy --paths.dev ./data/annotation/validation.spacy --gpu-id 0
  #   deps:
  #     - data/annotation/train.spacy
  #     - data/annotation/validation.spacy
  #   outs: 
  #     - models/spacy-ner
    
      
  # finetune_forward_lm:
  #   cmd: pipenv run python src/ner/flair/train_language_model.py --out=models/jobs_lm_forward --forward
  #   deps:
  #     - src/ner/flair/train_language_model.py
  #     - data/corpus/jobs/train
  #     - data/corpus/jobs/valid.txt
  #     - data/corpus/jobs/test.txt
  #   params:
  #     - flair.language_model_train.num_epochs
  #   outs:
  #     - models/jobs_lm_forward/best-lm.pt 
  #     - models/jobs_lm_forward/checkpoint.pt:
  #         checkpoint: true   
  # finetune_backward_lm:
  #   cmd: pipenv run python src/ner/flair/train_language_model.py --out=models/jobs_lm_backward --backward
  #   deps:
  #     - src/ner/flair/train_language_model.py
  #     - data/corpus/jobs/train
  #     - data/corpus/jobs/valid.txt
  #     - data/corpus/jobs/test.txt
  #   params:
  #     - flair.language_model_train.num_epochs
  #   outs:
  #     - models/jobs_lm_backward/best-lm.pt   
  #     - models/jobs_lm_backward/checkpoint.pt:
  #         checkpoint: true 
