stages:
  prepare_annotations:
    cmd: pipenv run python ./src/ner/convert_bliou_to_bio.py ./data/annotation/annotation-result-orig.txt
      ./data/annotation/annotation-result.txt --out data/annotation/annotation-result-BIO.txt
    deps:
      - ./src/ner/convert_bliou_to_bio.py
      - data/annotation/annotation-result-orig.txt
      - data/annotation/annotation-result.txt
    outs:
      - data/annotation/annotation-result-BIO.txt
  prepare_language_model_train_set:
    cmd: pipenv run python ./src/ner/flair/prepare_lm_train_files.py ./data/jobs/seek_vacancies.db
    deps:
      - ./src/ner/flair/prepare_lm_train_files.py
      - data/jobs/seek_vacancies.db
    params:
      - flair.language_model_train.corpus_dir
    outs:
      - data/corpus/jobs
