stages:
  prepare_annotations:
    cmd: pipenv run python ./src/ner/convert_bliou_to_bio.py ./data/annotation/annotation-result-orig.txt
      ./data/annotation/annotation-result.txt --out data/annotation/annotation-result-BIO.txt
    deps:
    - ./src/ner/convert_bliou_to_bio.py
    - data/annotation/annotation-result-orig.txt
    - data/annotation/annotation-result.txt
    outs:
    - data/annotation/annotation-result-BIO.txt
