stages:
  prepare_annotations:
    cmd: pipenv run python ./src/ner/convert_bliou_to_bio.py ./data/annotation/annotation-result-orig.txt
      ./data/annotation/annotation-result.txt --out data/annotation/annotation-result-BIO.txt
    deps:
      - ./src/ner/convert_bliou_to_bio.py
      - data/annotation/annotation-result-orig.txt
      - data/annotation/annotation-result.txt
    outs:
      - data/annotation/annotation-result-BIO.txt
  prepare_language_model_train_set:
    cmd: pipenv run python ./src/ner/flair/prepare_lm_train_files.py ./data/jobs/seek_vacancies.db
    deps:
      - ./src/ner/flair/prepare_lm_train_files.py
      - data/jobs/seek_vacancies.db
    params:
      - flair.language_model_train.corpus_dir
    outs:
      - data/corpus/jobs
  finetune_forward_lm:
    cmd: pipenv run python src/ner/flair/train_language_model.py --out=models/jobs_lm_forward --forward
    deps:
      - src/ner/flair/train_language_model.py
      - data/corpus/jobs
    params:
      - flair.language_model_train.num_epochs
    outs:
      - models/jobs_lm_forward    
  finetune_backward_lm:
    cmd: pipenv run python src/ner/flair/train_language_model.py --out=models/jobs_lm_backward --backward
    deps:
      - src/ner/flair/train_language_model.py
      - data/corpus/jobs
    params:
      - flair.language_model_train.num_epochs
    outs:
      - models/jobs_lm_backward