flair:
  language_model_train:
    num_epochs: 2
    corpus_dir: data/corpus/jobs
  ner_train:
    num_epochs: 40
    crf: True
    rnn: False
  ner_model: models/flair-ner-bert/best-model.pt
db: 
  jobs:
    connection_string: sqlite:///data/jobs/seek_vacancies.db 
